# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
data = [{:title=>"Beefy rice",
  :instructions=>
   "mix the beef with the cooking wine, starch, sugar, and a tbsp of soy sauce. let it marinate on the counter or in the fridge for 10 mins or so while you prep the other stuff\n" +
   "\n" +
   "add oil to the pan and get it smoking hot. throw your beef in there until the pink color is mostly gone. add the garlic and ginger to it and stir it frequently. remove from pan.\n" +
   "\n" +
   "add a bit more oil and saute the mushrooms, set them aside, then saute the vegetables (unless you would prefer them raw). add it all to a bowl of rice.",
  :ingredients_attributes=>
   [{:title=>"a little bit of beef, 1/4 pound or something", :position=>0},
    {:title=>"1 tbsp shaoxing cooking wine", :position=>1},
    {:title=>"1/2 tsp corn starch", :position=>2},
    {:title=>"soy sauce", :position=>3},
    {:title=>"1 tsp sugar", :position=>4},
    {:title=>"1 tbsp canola or vegetable oil", :position=>5},
    {:title=>"1 tbsp minced garlic", :position=>6},
    {:title=>"1 tbsp minced ginger", :position=>7},
    {:title=>"a few handfuls sliced mushrooms (shiitake, or whatever)",
     :position=>8},
    {:title=>
      "any other vegetables in your fridge (cabbage, broccoli, bell peppers, etc)",
     :position=>9},
    {:title=>"steamed rice", :position=>10}]},
 {:title=>"Easy Pork Rillettes (Slow-Cooked Pork Spread) Recipe",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>
      "2 pounds boneless, skinless pork shoulder, cut into 1 1/2-inch chunks (about 1kg)",
     :position=>0},
    {:title=>"Kosher salt", :position=>1},
    {:title=>"1/2 cup vegetable oil, lard, or duck fat (120ml)", :position=>2},
    {:title=>"4 bay leaves", :position=>3},
    {:title=>"6 fresh thyme sprigs", :position=>4},
    {:title=>"2 large shallots, very roughly chopped", :position=>5},
    {:title=>"4 medium cloves garlic, split in half", :position=>6},
    {:title=>"Freshly ground nutmeg, to taste", :position=>7}]},
 {:title=>"Cold-Processed Shrub Recipe",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>
      "1 cup berries or other fruit, washed and quartered or lightly crushed",
     :position=>0},
    {:title=>"1 cup sugar", :position=>1},
    {:title=>"1 cup red wine vinegar or apple-cider vinegar", :position=>2}]},
 {:title=>"orange julius",
  :instructions=>"chuck this stuff in the blender, zing it around",
  :ingredients_attributes=>
   [{:title=>"1/4 c milk", :position=>0},
    {:title=>"two oranges, peeled", :position=>1},
    {:title=>"1 tbsp sugar", :position=>2},
    {:title=>"3/4 c ice, about 4 normal cubes", :position=>3},
    {:title=>"1/4 tsp vanilla extract", :position=>4}]},
 {:title=>"Piña Colada",
  :instructions=>"throw it in a blender, serve in chilled glasses",
  :ingredients_attributes=>
   [{:title=>"chunks of frozen pineapple", :position=>0},
    {:title=>"2 oz coconut milk", :position=>1},
    {:title=>"2 oz rum (white, silver, dark, whatever)", :position=>2},
    {:title=>"1 lime, peeled", :position=>3},
    {:title=>"ice", :position=>4}]},
 {:title=>"Tiramisu II Recipe - Allrecipes.com",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"6 egg yolks", :position=>0},
    {:title=>"3/4 cup white sugar", :position=>1},
    {:title=>"2/3 cup milk", :position=>2},
    {:title=>"1 1/4 cups heavy cream", :position=>3},
    {:title=>"1/2 teaspoon vanilla extract", :position=>4},
    {:title=>"1 pound mascarpone cheese", :position=>5},
    {:title=>"1/4 cup strong brewed coffee, room temperature", :position=>6},
    {:title=>"2 tablespoons rum", :position=>7},
    {:title=>"2 (3 ounce) packages ladyfinger cookies", :position=>8},
    {:title=>"1 tablespoon unsweetened cocoa powder", :position=>9}]},
 {:title=>"Homemade Vegan Kimchi",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>
      "1 large head napa cabbage, cored and separated into individual leaves, about 1 pound total",
     :position=>0},
    {:title=>"1 small daikon radish (about 4 ounces)", :position=>1},
    {:title=>"8 scallions, greens roughly chopped, whites reserved separately",
     :position=>2},
    {:title=>"Kosher salt", :position=>3},
    {:title=>"8 cloves garlic", :position=>4},
    {:title=>"One 2-inch knob ginger, peeled", :position=>5},
    {:title=>"1/2 cup Korean chili powder (kochukaru)", :position=>6},
    {:title=>"2 tablespoons white or red miso paste", :position=>7},
    {:title=>"1 tablespoon sugar", :position=>8}]},
 {:title=>"Gingerbread Cookies 🌲",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"FOR THE COOKIE:", :position=>0},
    {:title=>"6 cups All-purpose Flour", :position=>1},
    {:title=>"1 teaspoon Salt", :position=>2},
    {:title=>"1/2 teaspoon Allspice", :position=>3},
    {:title=>"1/2 teaspoon Ground Cloves", :position=>4},
    {:title=>"1/2 teaspoon Ground Ginger", :position=>5},
    {:title=>"1/2 teaspoon Ground Nutmeg", :position=>6},
    {:title=>"1/2 teaspoon Ground Cinnamon", :position=>7},
    {:title=>"3/4 cups Margarine Or Softened Butter", :position=>8},
    {:title=>"1-1/2 cup Firmly Packed Dark Brown Sugar", :position=>9},
    {:title=>"1 cup Molasses", :position=>10},
    {:title=>"2 whole Eggs", :position=>11},
    {:title=>"1 Tablespoon Maple Extract", :position=>12},
    {:title=>"FOR THE ROYAL ICING:", :position=>13},
    {:title=>"2 pounds Powdered Sugar, Sifted", :position=>14},
    {:title=>"1/3 cup Whole Milk, Plus More If Needed For Thinning",
     :position=>15},
    {:title=>"2 whole Large Egg Whites", :position=>16},
    {:title=>"Miscellaneous Candies, Sprinkles, And Other Decorations",
     :position=>17}]},
 {:title=>"Basic Pesto Recipe",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"2 cups fresh basil leaves (no stems)", :position=>0},
    {:title=>"2 tablespoons pine nuts or walnuts", :position=>1},
    {:title=>"2 large cloves garlic", :position=>2},
    {:title=>"½ cup extra-virgin olive oil", :position=>3},
    {:title=>"½ cup freshly grated parmesan cheese", :position=>4}]},
 {:title=>"WW tortillas",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"2 cups white whole wheat flour", :position=>0},
    {:title=>"3 Tbsp extra virgin olive oil", :position=>1},
    {:title=>"1/2 tsp salt", :position=>2},
    {:title=>"2/3 c warm water", :position=>3}]},
 {:title=>"Veeg Enchiladas", :instructions=>"", :ingredients_attributes=>[]},
 {:title=>"Spiced Red Lentil, Tomato, and Kale Soup – Oh She Glows",
  :instructions=>"",
  :ingredients_attributes=>[]},
 {:title=>"benihana salad dressing",
  :instructions=>
   "toss everything into running blender in this order: ginger, carrot, onion, vinegar, soy sauce, sugar. slowly drizzle in oil to emulsify.",
  :ingredients_attributes=>
   [{:title=>"two inch chunk of ginger", :position=>0},
    {:title=>"1/4 cup chopped carrot", :position=>1},
    {:title=>"1/4 cup roughly chopped onion", :position=>2},
    {:title=>"2 tbsp rice vinegar", :position=>3},
    {:title=>"1 tbsp soy sauce", :position=>4},
    {:title=>"1/2 tsp sugar", :position=>5},
    {:title=>"1 tsp sesame oil", :position=>6},
    {:title=>"1/4 cup vegetable oil", :position=>7},
    {:title=>"salt", :position=>8}]},
 {:title=>"a beer",
  :instructions=>"drink the beer",
  :ingredients_attributes=>[{:title=>"a beer", :position=>0}]},
 {:title=>"Budget pesto",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"2 cups gently packed fresh basil leaves", :position=>0},
    {:title=>"2 large garlic cloves, roughly chopped", :position=>1},
    {:title=>"1/2 cup grated Parmigiano-Reggiano", :position=>2},
    {:title=>"1/3 cup walnuts", :position=>3},
    {:title=>"1/2 teaspoon salt", :position=>4},
    {:title=>"1/4 teaspoon ground black pepper", :position=>5},
    {:title=>
      "2/3 cup extra virgin olive oil, best quality such as Lucini or Colavita",
     :position=>6}]},
 {:title=>"Royal Icing Recipe for a Gingerbread House",
  :instructions=>"",
  :ingredients_attributes=>[]},
 {:title=>"Thai Beef Jerky",
  :instructions=>
   "roughly chop up and add the garlic, chilis, shallot, lime leaves and palm sugar to a mortar and pestle and smash them until a rough paste is formed. add soy sauce, fish sauce, and salt and mix into a paste. food processor works too. mix the beef with the paste in a big bowl and let marinate overnight.\n" +
   "\n" +
   "sprinkle some chili flakes onto the beef and stir. move strips of jerky into dehydrator at 160, or into oven at lowest temperature on a baking sheet with wire rack.",
  :ingredients_attributes=>
   [{:title=>
      "1 kg beef that's suitable for jerky, i.e. lean and cheap, sliced into 1/8\" strips",
     :position=>0},
    {:title=>"40 g soy sauce", :position=>1},
    {:title=>"70 g fish sauce", :position=>2},
    {:title=>"5 thai bird chilis", :position=>3},
    {:title=>"50 g palm sugar", :position=>4},
    {:title=>"8 makrut lime leaves, cut into small strips", :position=>5},
    {:title=>"1 shallot", :position=>6},
    {:title=>"dried thai chili flakes", :position=>7},
    {:title=>"12 cloves garlic", :position=>8},
    {:title=>"juice of 1 lime", :position=>9}]},
 {:title=>"How to Make Enchilada Sauce - Cookie and Kate",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"3 tablespoons olive oil", :position=>0},
    {:title=>
      "3 tablespoons flour (whole wheat flour, all-purpose flour and gluten-free flour blends all work!)",
     :position=>1},
    {:title=>
      "1 tablespoon ground chili powder (scale back if you’re sensitive to spice or using particularly spicy chili powder)",
     :position=>2},
    {:title=>"1 teaspoon ground cumin", :position=>3},
    {:title=>"½ teaspoon garlic powder", :position=>4},
    {:title=>"¼ teaspoon dried oregano", :position=>5},
    {:title=>"¼ teaspoon salt, to taste", :position=>6},
    {:title=>"Pinch of cinnamon (optional but recommended)", :position=>7},
    {:title=>"2 tablespoons tomato paste", :position=>8},
    {:title=>"2 cups vegetable broth", :position=>9},
    {:title=>"1 teaspoon apple cider vinegar or distilled white vinegar",
     :position=>10},
    {:title=>"Freshly ground black pepper, to taste", :position=>11}]},
 {:title=>"Homemade Coconut Milk Recipe | Wellness Mama",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>"4 cups of water", :position=>0},
    {:title=>"1.5-2 cups of unsweetened shredded coconut", :position=>1}]},
 {:title=>"Chickpea Cauliflower Curry Recipe | ChefDeHome.com",
  :instructions=>"",
  :ingredients_attributes=>
   [{:title=>
      "1/2 lbs Cauliflower (half head of medium cauliflower, broken into florets)",
     :position=>0},
    {:title=>"2 Cup Chickpeas (16 ounce can, drained)", :position=>1},
    {:title=>
      "1 tbsp Ginger Garlic Paste (3 cloves of garlic and 1 inch ginger, grated)",
     :position=>2},
    {:title=>"1.5 tbsp Tomato Paste", :position=>3},
    {:title=>
      "1 tbsp Curry Powder (I use madras curry powder, Or mix own spices. look for recipe in notes.)",
     :position=>4},
    {:title=>"1/2 tsp Chili Powder (or medium paprika)", :position=>5},
    {:title=>"1 Cup Coconut milk (low-fat or lite coconut milk)",
     :position=>6},
    {:title=>"1 Cup Vegetable Stock", :position=>7},
    {:title=>"2 tbsp Lime (juice, more per taste)", :position=>8},
    {:title=>"2 tbsp Canola Oil", :position=>9},
    {:title=>"1/2 tsp Salt (adjust per taste)", :position=>10},
    {:title=>"1 Whole Red Chili (optional)", :position=>11},
    {:title=>"1/2 Red Onion (thin sliced)", :position=>12},
    {:title=>"Rice", :position=>13},
    {:title=>"1/3 Cup Cashew (10-12 pieces, toasted or fried)", :position=>14},
    {:title=>"3-4 tbsp Cilantro (for garnish)", :position=>15}]}]

Recipe.create(data)
